config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/posts/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :posts
  get "/posts/:id" => "posts#show", as: :post
  get "/posts" => "posts#index"
  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"
  delete "/posts/:id" => "posts#destroy"

  get "/searches" => "searches#index"

  post "/comments" => "comments#create", as: :comments
  get "/comments/:id" => "comments#show", as: :comment
  get "/comments/:id/edit" => "comments#edit", as: :edit_comment
  patch "/comments/:id" => "comments#update"
  delete "/comments/:id" => "comments#destroy"

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  end

  resources :users, only: [:create, :new, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: :index

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/update_password" => "users#update_password", as: :update_password

  resources :password_resets

   root 'welcome#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user_id, :post_id, presence: true

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @posts = current_user.favored_posts
  end

  def create
    @post = Post.friendly.find params[:post_id]
    favor = Favorite.new(post: @post, user: current_user)
    respond_to do |format|
      if favor.save
         format.html { redirect_to post_path(@post), notice: "Added to your favorite" }
         format.js { render :successful_favor }

      else
         format.html { redirect_to post_path(@post), alert: "it is already added to your favorite" }
         format.js { redner :unsuccessful_favor }
      end
    end
  end

  def destroy
    @post = Post.friendly.find params[:post_id]
    favor = current_user.favorites.find params[:id]
    respond_to do |format|
      favor.destroy
      format.html { redirect_to post_path(@post), alert: "removed!" }
      format.js { render }
   end
  end
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/views/favorites/_post_favor.html.erb
<% favor = @post.favor_for(current_user) %>
<% if favor %>
<%= link_to icon("thumbs-up"), post_favorite_path(@post, favor), method: :delete, remote: true %>
<% else %>
<%= link_to icon("thumbs-o-up"), post_favorites_path(@post), method: :post, remote: true %>
<% end %>
(<%= @post.favorites.count %>)

app/views/favorites/destroy.js.erb
$("#favorite-post").html('<%= j render "post_favor" %>');

app/views/favorites/index.html.erb
<div class="container-fluid">
  <h1>Favorite Posts</h1>
</div>

<div class="container">
  <% @posts.each do |post| %>
  <div class="btn btn-default btn-lg">
  <h3><a href="#favorite-post-collapse" data-toggle="collapse"><%= post.title %><span class="caret"></span></a></h3>
  <div id="favorite-post-collapse" class="collapse" >
  <p>by: <%= post.user.first_name %></p>
  <p><%= link_to "View", post_path(post) %></p>
</div>
  <% end %>
</div>
</div>

app/views/favorites/successful_favor.js.erb
$('#favorite-post').html('<%= j render "post_favor" %>');

app/views/favorites/unsuccessful_favor.js.erb
alert("it may already be favored");
window.location.reload();