config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/posts/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :posts
  get "/posts/:id" => "posts#show", as: :post
  get "/posts" => "posts#index"
  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"
  delete "/posts/:id" => "posts#destroy"

  get "/searches" => "searches#index"

  post "/comments" => "comments#create", as: :comments
  get "/comments/:id" => "comments#show", as: :comment
  get "/comments/:id/edit" => "comments#edit", as: :edit_comment
  patch "/comments/:id" => "comments#update"
  delete "/comments/:id" => "comments#destroy"

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  end

  resources :users, only: [:create, :new, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: :index

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/update_password" => "users#update_password", as: :update_password

  resources :password_resets

   root 'welcome#index'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :text
#

class Comment < ActiveRecord::Base
  belongs_to :post

  belongs_to :user
  # after_save :organize_by_recent_date

  validates :body, presence: true, uniqueness: { scope: :post_id }

  scope :by_most_recent, -> { order(created_at: :desc) }

  # def self.organize_by_recent_date
  #   order(created_at: :desc)
  # end
end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :text
#

class CommentsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :delete]
  load_and_authorize_resource


  def index
    @comments = Comment.all

  end

  def new
    # @comment = Comment.new
  end

  def create
    @post = Post.friendly.find params[:post_id]
    # need to get the post_id
    # need to store
    @comment = Comment.new(comment_params)
    # The following code is creating post_id
    # @comment.post_id = @post.id (both are same)
    @comment.post = @post
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        #  CommentsMailer.notify_post_owner(@comment).deliver_later
         format.html {redirect_to post_path(@post), notice: "You have commented!"}
         format.js { render :successful_comment}
      else
         format.html {render :new}
         format.js { render :unsucessful_comment}
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.slug = nil
    if @comment.update(comment_params)
      redirect_to comment_path(@comment), notice: "Your comment has been updated!"
    else
      flash[:alert] = "Your comment is not updated!"
      render :edit
    end
  end

  def destroy
    respond_to do |format|
      @comment.destroy
      format.html {redirect_to post_path(params[:post_id]), notice: "Comment Deleted!"}
      format.js {render}
    end
  end

  private

  def find_post
    @post = Post.friendly.find(params[:post_id])
  end

  def comment_params
     params.require(:comment).permit([:body])
  end

end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  body       :text
#

module CommentsHelper
end

app/views/comments/_comments.html.erb
<div id="<%= dom_id(comment) %>" class="container">
  <div class="well well-sm comments-well-color">
      <p><strong><%= comment.user.first_name %></strong> <%= comment.body %>
      <%= comment.created_at.strftime("%Y-%b-%d") %>
    <% if can? :destroy, comment %>
    <%= link_to icon("pencil"), post_comment_path(@post, comment),
    method: :delete,
    remote: true,
    data: { confirm: "Are you Sure?"} %></p>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= @comment.errors.full_messages.join(", ") %>

<%= simple_form_for [@post, @comment], remote: true do |f| %>
  <%= f.input :body, label: false %>
  <%= f.button :submit%>
  <% end %>

app/views/comments/destroy.js.erb
$('#<%= dom_id(@comment) %>').fadeOut(1000, function() {$(this).remove()});

app/views/comments/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/comments/show.html.erb
<h1>Body: <%= @comment.body  %></h1>
<p>Created At: <%= @comment.created_at  %></p>
<p>Name: <%= @comment.user.full_name  %></p>

<%= link_to "Edit", edit_comment_path  %>
<%= link_to "Delete", comment_path(@comment),
                      method: :delete,
                      data: { confirm: "Are You Sure?"} %>
<%= link_to "Add", new_comment_path  %>

app/views/comments/successful_comment.js.erb
$('#comments').prepend("<%= j render 'comments', comment: @comment %>")

<% @comment = Comment.new %>

$('#comment-form').html('<%= j render "form" %>')

app/views/comments/unsucessful_comment.js.erb
$('comment-form').html("<%= j render 'form' %>")