config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/posts/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :posts
  get "/posts/:id" => "posts#show", as: :post
  get "/posts" => "posts#index"
  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"
  delete "/posts/:id" => "posts#destroy"

  get "/searches" => "searches#index"

  post "/comments" => "comments#create", as: :comments
  get "/comments/:id" => "comments#show", as: :comment
  get "/comments/:id/edit" => "comments#edit", as: :edit_comment
  patch "/comments/:id" => "comments#update"
  delete "/comments/:id" => "comments#destroy"

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  end

  resources :users, only: [:create, :new, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: :index

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/update_password" => "users#update_password", as: :update_password

  resources :password_resets

   root 'welcome#index'

end

app/models/user.rb
require 'securerandom'
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favored_posts, through: :favorites, source: :post

  attr_accessor :current_password

  validates :first_name, presence: true

  validates :last_name, presence: true

  validates :email, presence: true,
                    uniqueness: true,
                    format: /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :password, presence: true, if: :changing_password?

  validates :password_confirmation, presence: true, if: :changing_password?

  before_create { generate_token(:auth_token)}

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def full_name
    "#{first_name} #{last_name}".titleize
  end

  private

  def changing_password?
    current_password.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email,
                                               :password, :password_confirmation,
                                               :auth_token, :password_reset_token,
                                               :password_reset_sent_at)
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Account has been created!"
    else
      flash[:alert] = "Account wasn't created!"
      render :new
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    user_params = params.require(:user).permit(:first_name, :last_name, :email)
    @user = User.find params[:id]
    if @user.update(user_params)
      redirect_to root_path, notice: "Your Information has been updated!"
    else
      flash[:alert] = "Your Information wasn't updated!"
      render :edit
    end
  end


  def edit_password
    @user = User.find params[:id]
  end

  def update_password
    @user = User.find params[:id]
    user_params = params.require(:user).permit(:current_password, :password, :password_confirmation)

    if @user.authenticate(user_params[:current_password]) && @user.update(user_params)
        redirect_to root_path, notice: "Your password has been updated!"
     else
       flash[:alert] = "Your password is not updated!"
       render :edit_password
     end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= @user.errors.full_messages.join(", ") %>
<div class="container">
  <div class="well simple-form">
    <h1>Update</h1>

    <%= simple_form_for @user do |f| %>
    <div>
      <%= f.input :first_name %>
    </div>
    <div>
      <%= f.input :last_name %>
    </div>
    <div>
      <%= f.input :email %>
    </div>
    <%= f.button :submit %>
    <% end %>
    <%= link_to "Change Password", edit_password_path(@user) %>
  </div>
</div>

app/views/users/edit_password.html.erb
<%= @user.errors.full_messages.join(", ") %>
<div class="container">
  <div class="well simple-form">
    <h1>Update password</h1>
    
    <%= simple_form_for @user, url: update_password_path  do |f| %>
    <div>
      <%= f.input :current_password %>
    </div>
    <div>
      <%= f.input :password %>
    </div>
    <div>
      <%= f.input :password_confirmation %>
    </div>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= @user.errors.full_messages.join(", ") %>
<div class="container-fluid">
  <div class="well simple-form">
    <div class="page-header">
      <h1>Sign up</h1>
    </div>
    <%= simple_form_for @user do |f| %>
    <div>
      <%= f.input :first_name %>
    </div>
    <div>
      <%= f.input :last_name %>
    </div>
    <div>
      <%= f.input :email %>
    </div>
    <div>
      <%= f.input :password %>
    </div>
    <div>
      <%= f.input :password_confirmation %>
    </div>
    <%= f.button :submit %>
    <% end %>
  </div>
</div>