config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get "/posts/new" => "posts#new", as: :new_post
  post "/posts" => "posts#create", as: :posts
  get "/posts/:id" => "posts#show", as: :post
  get "/posts" => "posts#index"
  get "/posts/:id/edit" => "posts#edit", as: :edit_post
  patch "/posts/:id" => "posts#update"
  delete "/posts/:id" => "posts#destroy"

  get "/searches" => "searches#index"

  post "/comments" => "comments#create", as: :comments
  get "/comments/:id" => "comments#show", as: :comment
  get "/comments/:id/edit" => "comments#edit", as: :edit_comment
  patch "/comments/:id" => "comments#update"
  delete "/comments/:id" => "comments#destroy"

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

  end

  resources :users, only: [:create, :new, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end

  resources :favorites, only: :index

  get "/users/:id/edit_password" => "users#edit_password", as: :edit_password
  patch "/users/:id/update_password" => "users#update_password", as: :update_password

  resources :password_resets

   root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">

</head>
<body class="extra-space-bottom">

  <nav class="navbar navbar-fixed-top">
    <div class="container btn-group" style="width: 100%">
        <button class="btn btn-default dropdown-toggle btn-group" type="button"
        id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="float: left;">
        <i class="fa fa-bars"></i> <span class="caret"></span>
      </button>

      <div class="navbar-header" style="float: right;">
        <a href="/">
          <%= image_tag "blog_logo.png"%>
        </a>
      </div>
      <h1 style="width: 50%; margin: 0 auto; text-align: center; font-family: 'Tangerine';
      font-size: 50px"><a href="/" style="text-decoration:none; color: inherit">BLOG</a></h1>
    </div>
  </nav>


  <div id="wrapper">
    <div id="sidebar-wrapper">
      <ul class='sidebar-nav'>
        <% if current_user %>
          <li><%= link_to edit_user_path(current_user), class: "navbar_menu_text" do %></li>
            <i class="fa fa-user"></i> <%= current_user.first_name %>
          <% end %>

          <li><%= link_to sessions_path, method: :delete, class: "navbar_menu_text" do %></li>
            <i class="fa fa-power-off"></i> Log-out
          <% end %>

        <% else %>

          <li><%= link_to new_session_path, class: "navbar_menu_text" do %></li>
            <i class="fa fa-sign-in"></i> Log-in
          <% end %>

          <li><%= link_to new_user_path, class: "navbar_menu_text" do %></li>
            <i class="fa fa-user-plus"></i>Sign-up
          <% end %>

        <% end %>

          <li class="divider"></li>
        <% if current_user %>
          <li><%= link_to new_post_path, class: "navbar_menu_text" do %></li>
            <i class="fa fa-plus"></i> New post
          <% end %>
        <% end %>

          <li><%= link_to posts_path, class: "navbar_menu_text" do %></li>
            <i class="fa fa-list"></i>Posts
          <% end %>

        <% if current_user %>
          <li><%= link_to favorites_path, class: "navbar_menu_text" do %></li>
            <i class="fa fa-thumbs-o-up"></i>Favorite Posts
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

  <%#= notice || alert %>
    <%#= form_tag("/searches", :method => "get") do %>
    <%#= text_field_tag :search, params[:search] %>
    <%#= submit_tag "Search", :name => nil %>
    <%# end %>



<%= yield %>

</body>
</html>